name: Validate

on:
  push:
  pull_request:

jobs:
  validate_hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        uses: hacs/action@main
        with:
          ignore: "brands"
          category: "integration"
  validate_hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        uses: home-assistant/actions/hassfest@master
